### ISSUE TITLE
Does not run on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by magdesign** [VISNode/VISNode#3]
On the search for a node base image editor a found your repo.

Tried to run VISNode on Ubuntu 18.04 LTS with ./visnode-linux.sh 
But it somehow throws an Exeption error.
Tested with: openjdk 11.0.4 2019-07-16
and: openjdk 12.0.2 2019-07-16

When I am guessing right it  should open some kind of GUI when executing the shellscript?

Here the error output:
https://gist.github.com/magdesign/8945174e252f580e3f7d4a2a1f6ae3c9

**Comment by JonataBecker** [comment]
One GUI dependence didn't have support for java 11.

In the realese 1.2.7 (https://github.com/VISNode/VISNode/releases/tag/1.2.7) the problem was solve
